services:
  nginx:
    build: .
    container_name: devom-proxy
    ports:
      - "127.0.0.2:80:80"
      - "127.0.0.2:443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
